### ISSUE TITLE
Help needed with configuring heirline to show active virtual env

### ISSUE THREAD

**Issue by Balssh** [rebelot/heirline.nvim#147]
Hi, I'm sorry if this is not the place to ask, but I couldn't find any answers on the internet. I want to have the virtual env on the statusline, but I don't know how to do it and I'm quite new to nvim configurations.
Any help much appreciated.

**Comment by PyDev19** [comment]
```lua
local Seperator = { provider = " | " }

local PythonEnv = {
	condition = function()
		local venv = os.getenv("VIRTUAL_ENV")
		return venv ~= nil
	end,
	update = { "DirChanged" },
	{
		provider = function()
			local output = vim.fn.system('python -c "import sys, os; print(os.path.basename(sys.prefix))"')
			return "python: " .. vim.trim(output)
		end,
		hl = { fg = "cyan", bold = true },
	},
	Seperator,
}

return PythonEnv
```

This does roughly what you want but it has a little problem:
It depends on the python enviornment of the directory you open in the base terminal in which neovim is running inside.

Basically:
If I run neovim in directory `~/foo` which has a python venv in it and then I change directory in neovim to `~/bar` then the venv stays because the terminal in which neovim is running in is still in `~/foo` which has a venv. So if you want to show a different venv then you have to make sure the terminal in which neovim is running inside is also in that directory with the different venv.

**Comment by rebelot** [comment]
The best solution is to rely on plugins that let you manage python virtual envs from nvim, then you can (likely) use some of the plugin api or internal variables to show the venv name on the statusline, something like `{ provider = function() return require'venv-plugin'.venv end }`
