### ISSUE TITLE
error i got

### ISSUE THREAD

**Issue by bryant-the-coder** [rebelot/heirline.nvim#20]
![image](https://user-images.githubusercontent.com/92417638/154874113-f51e7d8c-c65a-4e60-9b37-5b94f66dc488.png)

this is the error i got. i m following the cookbook

**Comment by rebelot** [comment]
This is happening because`diffDeleted` highlight is not defined at the time you are evaluating heirline config. Make sure to setup heirline after your colorscheme. Note that not all colorscheme may define `diffDeleted` as it is not a default highlight although it's commonly used by version-control plugins (i.e. gitsigns and fugitive). Alternatively, check the highlights defined by your colorscheme and just pick something that gives you some red (deleted) green (added) and yellow (changed) colors or whatever you prefer

**Comment by bryant-the-coder** [comment]
new to lua

**Comment by rebelot** [comment]
> but i follow this :)

I understand, but that is just an example configuration that _should work_ for almost everyone (and indeed it does). The function `utils.get_highlight` is useful to get the color value of highlights defined by your colorscheme, so that the statusline colors match your colorscheme. In your case, for some reason, your colorscheme does not define vcs highlights, hence you should either change colorscheme, change the highlight from which you retrieve del, add and change colors or manually define the missing highlight.

**Comment by bryant-the-coder** [comment]
hmm... i made my own colorscheme xD. Using it. I might add it. Thanks. Will ask more ques if i have any queries.

**Comment by bryant-the-coder** [comment]
diffDelete is using gitsigns?

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/astron.nvim/blob/master/lua/astron/others.lua#L100-L103

**Comment by rebelot** [comment]
> diffDelete is using gitsigns?

Yes. GitSignsAdd links to diffAdded by default, unless you override it with something else, which is completely fine.

> hmm... i made my own colorscheme xD. Using it. I might add it. Thanks. Will ask more ques if i have any queries.

Please remember that issues should be relevant to the project scope, not a general neovim Q&A. If your problem is the colorscheme and not heirline itself, I'd recommend you to move the discussion somewhere else, maybe reddit, and close this.
